services:
  db:
    image: postgres:15
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: ecommerceUser
      POSTGRES_PASSWORD: ecommercePassword
      POSTGRES_DB: ecommerceDb
    ports:
      - '5432:5432'
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: ecommerce-mailpit
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  ecommerce-db-data:
