/** Spanish labels for admin status enum values shown in badges and dropdowns. */
const ADMIN_STATUS_LABELS: Record<string, string> = {
  Draft: 'Borrador',
  Active: 'Activo',
  Inactive: 'Inactivo',
  Archived: 'Archivado',
  Blocked: 'Bloqueado',
  Synced: 'Sincronizado',
  Failed: 'Fallido',
  NotPromoted: 'Sin promocionar',
  Connected: 'Conectado',
  Disconnected: 'Desconectado',
  Error: 'Error',
  PendingPayment: 'Pago pendiente',
  Paid: 'Pagado',
  Processing: 'En proceso',
  Completed: 'Completado',
  Cancelled: 'Cancelado',
  Refunded: 'Reembolsado',
  Pending: 'Pendiente',
  Authorized: 'Autorizado',
  PartiallyRefunded: 'Reembolsado parcial',
  NotStarted: 'No iniciado',
  PendingSupplierOrder: 'Pendiente de pedido a proveedor',
  SupplierOrderPlaced: 'Pedido a proveedor realizado',
  PartiallyFulfilled: 'Parcialmente cumplido',
  Fulfilled: 'Cumplido',
  Requested: 'Solicitado',
  Confirmed: 'Confirmado',
  OutOfStock: 'Sin stock',
  Shipped: 'Enviado',
  Delivered: 'Entregado',
  Approved: 'Aprobado',
  Rejected: 'Rechazado',
  Received: 'Recibido',
  InTransit: 'En tránsito',
  Returned: 'Devuelto',
  SupplierManaged: 'Gestionado por proveedor',
  InternalStock: 'Stock interno',
  Hybrid: 'Híbrido',
  Shipping: 'Envío',
  Billing: 'Facturación',
};

export function adminStatusLabel(status: string): string {
  return ADMIN_STATUS_LABELS[status] ?? status;
}
