name: Semgrep

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: semgrep-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Run Semgrep
        run: semgrep scan --config auto --error
